[package]
name = 'rmzdb'
version = '0.2.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]

[dependencies]
anyhow = "*"
getset = "0.1.3"
mzdb-rs = { path = "../../../mzdb-rs" }
extendr-api = '0.7.1'
rusqlite = { version = "0.32.1" } # , features = ["blob","bundled"]